// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCamlHGGSTMet7kHoB2msERTPuguejJiJc',
    appId: '1:9471750815:web:75519e0e89594a3e2e28aa',
    messagingSenderId: '9471750815',
    projectId: 'finalproject-a3615',
    authDomain: 'finalproject-a3615.firebaseapp.com',
    storageBucket: 'finalproject-a3615.firebasestorage.app',
    measurementId: 'G-DHVYT5KRJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgzerKz2NtG51hccWO07SNHdVjmaTOyvI',
    appId: '1:9471750815:android:7b907c3fcec0d1e92e28aa',
    messagingSenderId: '9471750815',
    projectId: 'finalproject-a3615',
    storageBucket: 'finalproject-a3615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_8iUFwFow24ShEmUsKEvz4bgl0zv9Wig',
    appId: '1:9471750815:ios:3a6cb8fc821faa7e2e28aa',
    messagingSenderId: '9471750815',
    projectId: 'finalproject-a3615',
    storageBucket: 'finalproject-a3615.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_8iUFwFow24ShEmUsKEvz4bgl0zv9Wig',
    appId: '1:9471750815:ios:3a6cb8fc821faa7e2e28aa',
    messagingSenderId: '9471750815',
    projectId: 'finalproject-a3615',
    storageBucket: 'finalproject-a3615.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCamlHGGSTMet7kHoB2msERTPuguejJiJc',
    appId: '1:9471750815:web:2c08531bbe5949852e28aa',
    messagingSenderId: '9471750815',
    projectId: 'finalproject-a3615',
    authDomain: 'finalproject-a3615.firebaseapp.com',
    storageBucket: 'finalproject-a3615.firebasestorage.app',
    measurementId: 'G-JXHRRNH108',
  );
}
